language: java
jdk:
  - oraclejdk8
env:
  - MVN_VERSION=3.8.0
cache:
  directories:
    - $HOME/.m2
install: eval mvn clean
script: eval mvn install
after_success: eval mvn coveralls:report
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false